"use client";

import Link from "next/link";
import { useState } from "react";
import { useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";

export default function ApplicationsPage() {
  const [status, setStatus] = useState("all");
  const applications = useQuery(api.hiring.listApplications, { status });

  return (
    <div className="min-h-screen bg-gray-50 text-black">
      <div className="max-w-6xl mx-auto px-6 py-8 space-y-8">
        <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
          <div>
            <div className="text-xs uppercase tracking-[0.24em] text-gray-500 font-semibold">Application Queue</div>
            <h1 className="mt-2 text-3xl font-semibold tracking-tight">Review + Submission Pipeline</h1>
            <p className="mt-2 text-sm text-gray-600 max-w-3xl">
              Packages generated by the agents stay here until you approve, reject, or mark them submitted.
            </p>
          </div>
          <div className="flex gap-3">
            <Link href="/jobs" className="rounded-full border border-gray-200 bg-white px-4 py-2 text-sm font-medium hover:bg-gray-100">
              Back to Jobs
            </Link>
            <select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-full border border-gray-200 bg-white px-4 py-2 text-sm">
              <option value="all">All statuses</option>
              <option value="awaiting_approval">Awaiting approval</option>
              <option value="approved">Approved</option>
              <option value="submitted">Submitted</option>
              <option value="interview">Interview</option>
              <option value="reject">Reject</option>
              <option value="offer">Offer</option>
            </select>
          </div>
        </header>

        <section className="grid gap-4">
          {(applications ?? []).map((application) => (
            <Link key={application._id} href={`/applications/${application._id}`} className="rounded-3xl border border-gray-200 bg-white p-6 shadow-sm transition hover:border-black">
              <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                <div className="space-y-2">
                  <div className="flex flex-wrap items-center gap-2">
                    <h2 className="text-xl font-semibold">{application.job?.title ?? "Untitled role"}</h2>
                    <span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-medium text-gray-700">{application.job?.company ?? "Unknown company"}</span>
                    <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{application.status.replace(/_/g, " ")}</span>
                  </div>
                  <div className="text-sm text-gray-600">{application.job?.location ?? "Location unavailable"} · {application.source?.provider ?? "unknown source"}</div>
                  <div className="text-sm text-gray-600">Created {new Date(application.createdAt).toLocaleString()}</div>
                </div>
                <div className="grid grid-cols-2 gap-3 rounded-2xl bg-gray-50 p-4 text-sm min-w-[240px]">
                  <div>
                    <div className="text-xs uppercase tracking-[0.18em] text-gray-500">Signals</div>
                    <div className="mt-1 text-2xl font-semibold">{application.signalCount}</div>
                  </div>
                  <div>
                    <div className="text-xs uppercase tracking-[0.18em] text-gray-500">Updated</div>
                    <div className="mt-1 text-sm font-medium">{new Date(application.updatedAt).toLocaleDateString()}</div>
                  </div>
                </div>
              </div>
            </Link>
          ))}
          {(applications ?? []).length === 0 && (
            <div className="rounded-3xl border border-dashed border-gray-300 bg-white p-8 text-sm text-gray-600">
              No applications in this state yet.
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
